
-- CREAR BASE DE DATOS BD_DO --
CREATE DATABASE BD_DO;

-- USAR BASE DE DATOS BD_DO --
USE BD_DO;

-- CREAR TABLA CIUDADES --
CREATE TABLE TB_CIUDADES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	CIUDAD VARCHAR(255) NOT NULL,
	DEPARTAMENTO VARCHAR(255) NOT NULL,
	REGION VARCHAR(255) NOT NULL
);
GO

-- CREAR TABLA TIPO_LINEAS --
CREATE TABLE TB_TIPO_LINEAS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TIPO_LINEA VARCHAR(9) NOT NULL
);
GO

-- CREAR TABLA REDES SOCIALES --
CREATE TABLE TB_REDES_SOCIALES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	RED_SOCIAL VARCHAR(11) NOT NULL
);
GO

-- CREAR TABLA SUPERVISORES --
CREATE TABLE TB_SUPERVISORES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRES VARCHAR(255) NOT NULL,
	APELLIDO_PATERNO VARCHAR(255) NOT NULL,
	APELLIDO_MATERNO VARCHAR(255) NOT NULL,
	TIPO_DOCUMENTO VARCHAR(5) NOT NULL,
	NRO_DOCUMENTO VARCHAR(15) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(9) NOT NULL
);
GO

-- CREAR TABLA VENDEDORES --
CREATE TABLE TB_VENDEDORES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_SUPERVISOR INT NOT NULL,
	NOMBRES VARCHAR(255) NOT NULL,
	APELLIDO_PATERNO VARCHAR(255) NOT NULL,
	APELLIDO_MATERNO VARCHAR(255) NOT NULL,
	TIPO_DOCUMENTO VARCHAR(5) NOT NULL,
	NRO_DOCUMENTO VARCHAR(15) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(9) NOT NULL,
	CONSTRAINT FK_ID_SUPERVISOR FOREIGN KEY(ID_SUPERVISOR) REFERENCES TB_SUPERVISORES(ID)
);
GO

-- CREAR TABLA PLANES --
CREATE TABLE TB_PLANES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_TIPO_LINEA INT NOT NULL,
	NOMBRE_PLAN VARCHAR(255) NOT NULL,
	PRECIO MONEY NOT NULL,
	CONSTRAINT FK_ID_TIPO_LINEA FOREIGN KEY(ID_TIPO_LINEA) REFERENCES TB_TIPO_LINEAS(ID)
);
GO

-- CREAR TABLA CLIENTES --
CREATE TABLE TB_CLIENTES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_CIUDAD INT NOT NULL,
	NOMBRES VARCHAR(255) NULL,
	APELLIDO_PATERNO VARCHAR(255) NULL,
	APELLIDO_MATERNO VARCHAR(255) NULL,
	TIPO_DOCUMENTO VARCHAR(5) NULL,
	NRO_DOCUMENTO VARCHAR(15) NULL,
	SEXO CHAR(1) NULL,
	FECHA_NACIMIENTO DATE NULL,
	CORREO VARCHAR(255) NULL,
	TELEFONO CHAR(9) NULL,
	CONSTRAINT FK_ID_CIUDAD FOREIGN KEY(ID_CIUDAD) REFERENCES TB_CIUDADES(ID)
);
GO

-- CREAR TABLA VENTAS --
CREATE TABLE TB_VENTAS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_CLIENTE INT NOT NULL,
	ID_PLAN INT NOT NULL,
	ID_RED_SOCIAL INT NOT NULL,
	ID_VENDEDOR INT NOT NULL,
	NRO_TELEFONO CHAR(9) NULL,
	FECHA_ACTIVACION DATE NULL,
	TIPO_CONEXION VARCHAR(255) NULL,
	ESTADO_LINEA VARCHAR(255) NULL,
	CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES TB_CLIENTES(ID),
	CONSTRAINT FK_ID_PLAN FOREIGN KEY(ID_PLAN) REFERENCES TB_PLANES(ID),
	CONSTRAINT FK_ID_RED_SOCIAL FOREIGN KEY(ID_RED_SOCIAL) REFERENCES TB_REDES_SOCIALES(ID),
	CONSTRAINT FK_ID_VENDEDOR FOREIGN KEY(ID_VENDEDOR) REFERENCES TB_VENDEDORES(ID)
);

--- INSERTAR DATOS A LA TABLA REDES SOCIALES --
INSERT INTO TB_REDES_SOCIALES(RED_SOCIAL)
VALUES
	('Facebook'),
	('Whatsapp'),
	('Instagram');

-- INSERTAR DATOS A LA TABLA TIPO_LINEAS
INSERT INTO TB_TIPO_LINEAS(TIPO_LINEA)
VALUES
	('Prepago'),
	('Postpago');

-- RESTRINGIR DATOS EN TABLA CLIENTES --
ALTER TABLE TB_CLIENTES
ALTER COLUMN NOMBRES VARCHAR(255) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN APELLIDO_PATERNO VARCHAR(255) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN APELLIDO_MATERNO VARCHAR(255) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN TIPO_DOCUMENTO VARCHAR(5) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN NRO_DOCUMENTO VARCHAR(15) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN SEXO CHAR(1) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN FECHA_NACIMIENTO DATE NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN CORREO VARCHAR(255) NOT NULL;

ALTER TABLE TB_CLIENTES
ALTER COLUMN TELEFONO CHAR(9) NOT NULL;

-- RESTRINGIR DATOS EN TABLA VENTAS --
ALTER TABLE TB_VENTAS
ALTER COLUMN NRO_TELEFONO CHAR(9) NOT NULL;

ALTER TABLE TB_VENTAS
ALTER COLUMN FECHA_ACTIVACION DATE NOT NULL;

ALTER TABLE TB_VENTAS
ALTER COLUMN TIPO_CONEXION VARCHAR(255) NOT NULL;

ALTER TABLE TB_VENTAS
ALTER COLUMN ESTADO_LINEA VARCHAR(255) NOT NULL;